package com.yh.pojo;

import java.util.Date;

public class Passport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_passport.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_passport.nationality
     *
     * @mbggenerated
     */
    private String nationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_passport.expire
     *
     * @mbggenerated
     */
    private Date expire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_passport.passenger_id
     *
     * @mbggenerated
     */
    private Integer passengerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_passport.id
     *
     * @return the value of t_passport.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_passport.id
     *
     * @param id the value for t_passport.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_passport.nationality
     *
     * @return the value of t_passport.nationality
     *
     * @mbggenerated
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_passport.nationality
     *
     * @param nationality the value for t_passport.nationality
     *
     * @mbggenerated
     */
    public void setNationality(String nationality) {
        this.nationality = nationality == null ? null : nationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_passport.expire
     *
     * @return the value of t_passport.expire
     *
     * @mbggenerated
     */
    public Date getExpire() {
        return expire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_passport.expire
     *
     * @param expire the value for t_passport.expire
     *
     * @mbggenerated
     */
    public void setExpire(Date expire) {
        this.expire = expire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_passport.passenger_id
     *
     * @return the value of t_passport.passenger_id
     *
     * @mbggenerated
     */
    public Integer getPassengerId() {
        return passengerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_passport.passenger_id
     *
     * @param passengerId the value for t_passport.passenger_id
     *
     * @mbggenerated
     */
    public void setPassengerId(Integer passengerId) {
        this.passengerId = passengerId;
    }
}