package com.yh.mapper;

import com.yh.pojo.Passport;
import com.yh.pojo.PassportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PassportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_passport
     *
     * @mbggenerated
     */
    int countByExample(PassportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_passport
     *
     * @mbggenerated
     */
    int deleteByExample(PassportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_passport
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_passport
     *
     * @mbggenerated
     */
    int insert(Passport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_passport
     *
     * @mbggenerated
     */
    int insertSelective(Passport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_passport
     *
     * @mbggenerated
     */
    List<Passport> selectByExample(PassportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_passport
     *
     * @mbggenerated
     */
    Passport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_passport
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Passport record, @Param("example") PassportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_passport
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Passport record, @Param("example") PassportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_passport
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Passport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_passport
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Passport record);
}